---
# ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
# ansible_ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'ssh_private_key_file') }}"
timezone: "Asia/Colombo"

ha_access_user_name: haaccess
devops_access_user_name: devopsaccess
