---
ansible_ssh_extra_args: "-o IdentitiesOnly=yes"
ansible_ssh_private_key_file: ~/.ssh/id_ed25519_homelab_asiri-devops
server_admin_user: serveradmin
timezone: "Asia/Colombo"
ha_access_user: haaccess
local_backup_mount_point: /mnt/remote-backup
