## !important: password is not hashed
server_admin_user_password: "{{ lookup('ansible.builtin.env', 'admin_user_password') }}"

## access
ha_user_allowed_commands:
  - "{{ remote_script_directory }}/reboot.sh"
  - "{{ remote_script_directory }}/shutdown.sh"

devops_user_allowed_commands:
  - "{{ remote_script_directory }}/backup.sh"
  - "{{ remote_script_directory }}/init-restic-repository.sh"

## scripts
remote_script_directory: "/var/services/homes/{{ lookup('ansible.builtin.env', 'admin_user_name') }}/scripts"

mandatory_scripts:
  - "../launchpad-scripts/power/shutdown.sh"
  - "../launchpad-scripts/power/reboot.sh"

backup_script: "../launchpad-scripts/backup/synology/backup.sh"
backup_init_script: "../launchpad-scripts/backup/synology/init-restic-repository.sh"

include_file_list: "../launchpad-config/synology/include.txt"
exclude_file_list: "../launchpad-config/synology/exclude.txt"
