## !important: password is not hashed
server_admin_user_password: "{{ lookup('ansible.builtin.env', 'admin_user_password') }}"

remote_script_directory: "/var/services/homes/{{ lookup('ansible.builtin.env', 'admin_user_name') }}/scripts"

mandatory_scripts:
  - "../launchpad-scripts/power/shutdown.sh"
  - "../launchpad-scripts/power/reboot.sh"

backup_script: "../launchpad-scripts/general/backup-synology.sh"

ha_user_allowed_commands:
  - "{{ remote_script_directory }}/reboot.sh"
  - "{{ remote_script_directory }}/shutdown.sh"

devops_user_allowed_commands:
  - "{{ remote_script_directory }}/backup-synology.sh"
