- name: Install and Setup Restic
  ansible.builtin.include_role:
    name: setup_restic

- name: Initialize Repository
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/syno/sbin:/var/services/homes/{{ ansible_user }}/scripts"
  ansible.builtin.command: init-restic-repository.sh
  args:
    creates: "{{ remote_script_directory }}/restic-repo-inited"
