- name: Bootstrap Pi
  hosts: iris
  become: true
  roles:
    - role: rpi_bootstrap
    - role: apt_updates
  tags: bootstrap

- name: Setup docker
  hosts: iris
  become: true
  roles:
    - role: setup_docker
  tags: bootstrap

- name: Configure traefik
  hosts: iris
  roles:
    - role: copy_scripts
  vars:
    copy_scripts_modules:
      - "../launchpad-docker/traefik"
  tags: traefik

- name: Update Traefik Config
  hosts: iris
  roles:
    - role: docker_compose_service
      vars:
        docker_compose_service_path: "/home/{{ server_admin_user }}/traefik"
        docker_compose_service_files:
          - src: ../launchpad-docker/traefik/data/config.yaml
            dest: "/home/{{ server_admin_user }}/traefik/data/"
  tags: traefik-update
# - name: Copy module folders
#   hosts: iris
#   roles:
#     - role: copy_module_folders
#       vars:
#         modules:
#           portainer: '../docker/portainer'
#           dashy: '../docker/dashy'
#           'uptime-kuma': '../docker/uptime-kuma'
#           webnut: '../docker/webnut'
#           upsnap: '../docker/upsnap'
#           'orbital-sync': '../docker/orbital-sync'
#   tags: mods
