- name: Update Packages
  hosts: portainer_nodes
  roles:
    - role: apt-updates
  tags: bootstrap

- name: Setup docker
  hosts: portainer_nodes
  roles:
    - role: setup-docker
  tags: bootstrap

- name: Setup Primary Portainer Node
  hosts: iris
  roles:
    - role: copy-module-folders
      vars:
        modules:
          portainer: '../launchpad-docker/portainer'
    - role: update-docker-compose-service
      vars:
        compose_path: '/home/{{ server_admin_user }}/portainer'
  tags: primary

- name: Copy Portainer Agents to Slaves
  hosts: portainer_slaves
  roles:
    - role: copy-module-folders
      vars:
        modules:
          'portainer-agent': '../launchpad-docker/portainer-agent'
    - role: update-docker-compose-service
      vars:
        compose_path: '/home/{{ server_admin_user }}/portainer-agent'
  tags: slaves

# - name: Copy Modules to Portainer Slave-1
#   hosts: capella-vm-100
#   roles:
#     - role: copy-module-folders
#       vars:
#         modules:
#           netbox: '../docker/netbox'
#           netboot: '../docker/netboot'
#           paperless: '../docker/paperless'
#           syncthing: '../docker/syncthing'
#   tags: slave-1
# - name: Copy Modules to Portainer Slave-2
#   hosts: capella-vm-100
#   roles:
#     - role: copy-module-folders
#       vars:
#         modules:
#           # 'media-downloader': '../docker/media-downloader'
#           # syncthing: '../docker/syncthing'
#   tags: slave-2
