- name: Set Detected System
  hosts: synology_storage_nodes
  roles:
    - role: set-detected-system
  tags:
    - scripts
    - backup

- name: Setup Mandatory Scripts
  hosts: synology_storage_nodes
  roles:
    - role: copy-scripts
      vars:
        scripts: "{{ mandatory_scripts }}"
        remote_directory: "{{ remote_script_directory }}/"
        group_name: devops
  tags: scripts

- name: Prepare BackUp Config
  hosts: synology_storage_nodes
  roles:
    - role: copy-scripts
      vars:
        scripts:
          - "{{ backup_script }}"
        remote_directory: "{{ remote_script_directory }}/"
        group_name: devops

    - role: setup-backup-config
      become: true
      vars:
        remote_backup_path: "{{ lookup('ansible.builtin.env', 'remote_backup_path') }}"
        local_backup_mount_point: "{{ lookup('ansible.builtin.env', 'local_backup_mount_point') }}"
  tags: backup
