- name: Bootstrap Pi
  hosts: iris
  become: true
  roles:
    - role: rpi_bootstrap
    - role: apt_updates
  tags: bootstrap

- name: Setup docker
  hosts: iris
  become: true
  roles:
    - role: setup_docker
  tags: bootstrap

- name: Configure traefik
  hosts: iris
  roles:
    - role: copy_scripts
  vars:
    copy_scripts_modules:
      - "../launchpad-docker/traefik_v3"
  tags: traefik

- name: Update Traefik Config
  hosts: iris
  roles:
    - role: docker_compose_service
      vars:
        docker_compose_service_container_name: "traefik"
        docker_compose_service_path: "/home/{{ server_admin_user_name }}/traefik_v3"
        docker_compose_service_src: '../launchpad-docker/traefik_v3/data/config.yaml'
        docker_compose_service_dest: "/home/{{ server_admin_user_name }}/traefik_v3/data/"
        docker_compose_service_owner: "{{ server_admin_user_name }}"
        docker_compose_service_group: "{{ server_admin_user_name }}"
  tags: traefik-update

- name: Copy Manifests
  hosts: iris
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_dest: '/home/{{ server_admin_user_name }}/'
        copy_scripts_group_name: "{{ server_admin_user_name }}"
        copy_scripts_filelist:
          - '../launchpad-docker/homepage'
  tags: mods
