- name: Install Prerequisites
  hosts: all
  roles:
    - role: ansible-prerequisites
  tags: init

- name: Create Server Admin User
  hosts: all
  roles:
    - role: add-sudo-user
      vars:
        username: "{{ server_admin_user_name }}"
        password: "{{ server_admin_user_password }}"
        user_shell: '/bin/bash'
        admin_groups:
          - devops
  tags: superuser

- name: Merge public keys
  hosts: all
  roles:
    - role: update-authorized-key
      vars:
        username: "{{ lookup('ansible.builtin.env', 'admin_user_name') }}"
        keys:
          - id_ed25519_homelab_asiri-devops
  tags: mergekeys
