- name: Install Prerequisites
  hosts: all
  gather_facts: false
  roles:
    - role: ansible-prerequisites
  tags: init

- name: Create Server Admin User
  hosts: all
  vars:
    username: '{{ server_admin_user }}'
    password: "{{ '4TuDsZAbPaN4' | password_hash('sha512') }}"
    user_shell: '/bin/bash'
  roles:
    - role: add-sudo-user
  tags: superuser

- name: Merge public keys
  hosts: all
  roles:
    - role: update-authorized-key
  vars:
    username: '{{ server_admin_user }}'
    keys:
      - id_ed25519_homelab_asiri-devops
      # - id_ed25519_homelab_ha-access
  tags: mergekeys
