- name: Update Packages
  hosts: portainer_nodes
  roles:
    - role: apt_updates
  tags: bootstrap

- name: Setup docker
  hosts: portainer_nodes
  roles:
    - role: setup_docker
  tags: bootstrap

- name: Setup Primary Portainer Node
  hosts: iris
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_modules:
          - "../launchpad-docker/portainer"
    - role: docker_compose_service
      vars:
        docker_compose_service_path: "/home/{{ server_admin_user }}/portainer"
  tags: primary

- name: Copy Portainer Agents to Slaves
  hosts: portainer_slaves
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_modules:
          - "../launchpad-docker/portainer-agent"
    - role: docker_compose_service
      vars:
        docker_compose_service_path: "/home/{{ server_admin_user }}/portainer-agent"
  tags: slaves
# - name: Copy Modules to Portainer Slave-1
#   hosts: capella-vm-100
#   roles:
#     - role: copy_module_folders
#       vars:
#         modules:
#           netbox: '../docker/netbox'
#           netboot: '../docker/netboot'
#           paperless: '../docker/paperless'
#           syncthing: '../docker/syncthing'
#   tags: slave-1
# - name: Copy Modules to Portainer Slave-2
#   hosts: capella-vm-100
#   roles:
#     - role: copy_module_folders
#       vars:
#         modules:
#           # 'media-downloader': '../docker/media-downloader'
#           # syncthing: '../docker/syncthing'
#   tags: slave-2
