- name: Set Detected System
  hosts: pihole_nodes
  roles:
    - role: set_detected_system
  tags:
    - bootstrap
    - backup
    - scripts
    - ha
    - master
    - slaves
    - docker
    - module

- name: Bootstrap Device
  hosts: pihole_nodes
  become: true
  roles:
    - role: system_service
      vars:
        system_service_name: keepalived
        system_service_state: stopped
    - role: rpi_bootstrap
    - role: apt_updates
    - role: system_service
      vars:
        system_service_name: keepalived
        system_service_state: started
  tags: bootstrap

- name: Setup Mandatory Scripts
  hosts: pihole_nodes
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_filelist: '{{ mandatory_scripts }}'
        copy_scripts_dest: '{{ remote_script_directory }}/'
        copy_scripts_group_name: devops
  tags: scripts

- name: Prepare BackUp Config
  hosts: pihole_nodes
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_filelist:
          - '{{ backup_script }}'
        copy_scripts_dest: '{{ remote_script_directory }}/'
        copy_scripts_group_name: devops

    - role: onsite_backup
      become: true
      vars:
        onsite_backup_backup_path: '{{ backup_remote_path }}'
        onsite_backup_mount_point: '{{ backup_local_mount_point }}'
  tags: backup

- name: Setup docker
  hosts: pihole_nodes
  become: true
  roles:
    - role: system_service
      vars:
        system_service_name: keepalived
        system_service_state: stopped
    - role: setup_docker
    - role: system_service
      vars:
        system_service_name: keepalived
        system_service_state: started
  tags: docker

- name: Manage PiHole Container
  hosts: pihole_nodes
  tasks:
    - name: Stop Container
      include_role:
        name: docker_compose_service
      vars:
        docker_compose_service_container_name: 'pihole'
        docker_compose_service_path: '/home/{{ server_admin_user_name }}/pihole'
        docker_compose_service_status: stopped

    - name: Copy Files
      ansible.builtin.copy:
        src: '../launchpad-docker/pihole'
        dest: '/home/{{ server_admin_user_name }}/'
        owner: '{{ server_admin_user_name }}'
        group: '{{ server_admin_user_name }}'

    - name: Replace 'fqdn' with hostname in .env file
      ansible.builtin.lineinfile:
        path: '/home/{{ server_admin_user_name }}/pihole/.env'
        regexp: '^PIHOLE_WEBSERVER_DOMAIN=fqdn$'
        line: 'PIHOLE_WEBSERVER_DOMAIN={{ ansible_hostname }}.local.theinquisitive.me'
        state: present

    - name: Start Container
      include_role:
        name: docker_compose_service
      vars:
        docker_compose_service_container_name: 'pihole'
        docker_compose_service_path: '/home/{{ server_admin_user_name }}/pihole'
        docker_compose_service_status: present
  tags: pihole

- name: Setup HA Master
  hosts: pihole_master
  become: true
  roles:
    - role: pihole_ha
      vars:
        pihole_ha_keepalived_vrrp_role: MASTER
        pihole_ha_keepalived_vrrp_priority: 100
        pihole_ha_keepalived_vrrp_preempt_delay: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_preempt_delay') }}"
        pihole_ha_keepalived_vrrp_password: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_password') }}"
        pihole_ha_keepalived_vrrp_vip_ipv4: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_vip') }}"
        pihole_ha_keepalived_vrrp_router_id: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_router_id') }}"
        pihole_ha_keepalived_unicast_peers: pihole_slaves
  tags:
    - ha
    - master

- name: Setup HA Slaves
  hosts: pihole_slaves
  become: true
  roles:
    - role: pihole_ha
      vars:
        pihole_ha_keepalived_vrrp_role: BACKUP
        pihole_ha_keepalived_vrrp_priority: 1
        pihole_ha_keepalived_vrrp_preempt_delay: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_preempt_delay') }}"
        pihole_ha_keepalived_vrrp_password: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_password') }}"
        pihole_ha_keepalived_vrrp_vip_ipv4: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_vip') }}"
        pihole_ha_keepalived_vrrp_router_id: "{{ lookup('ansible.builtin.env', 'pihole_keepalived_router_id') }}"
        pihole_ha_keepalived_unicast_peers: pihole_master
  tags:
    - ha
    - slaves
