- name: Install Prerequisites
  hosts: snipeit_box
  roles:
    - role: ansible_prerequisites
  tags: init

- name: Update Packages
  hosts: snipeit_box
  roles:
    - role: apt_updates
    - role: common_packages
  tags: bootstrap

- name: Setup docker
  hosts: snipeit_box
  roles:
    - role: setup_docker
  tags: bootstrap

- name: Copy Manifests
  hosts: snipeit_box
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_dest: '/home/{{ server_admin_user_name }}/'
        copy_scripts_group_name: "{{ server_admin_user_name }}"
        copy_scripts_filelist:
          - '../launchpad-docker/snipe-it'
  tags: mod
