- name: Add Sudo User
  hosts: all
  gather_facts: true # required to set the ansible_env
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/syno/sbin:/var/services/homes/{{ ansible_user }}/scripts"
  roles:
    - role: add-synology-sudo-user
      become: true
      vars:
        username: "{{ server_admin_user_name }}"
        password: "{{ server_admin_user_password }}"
        admin_groups:
          - administrators
          - devops
  tags: superuser

- name: Merge public keys
  hosts: all
  roles:
    - role: update-authorized-key
      become: true
      vars:
        username: "{{ server_admin_user_name }}"
        keys:
          - id_ed25519_homelab_asiri-devops
  tags: mergekeys
