- name: Set Detected System
  hosts: synology_storage_nodes
  roles:
    - role: set_detected_system
  tags:
    - scripts
    - backup

- name: Setup Mandatory Scripts
  hosts: synology_storage_nodes
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_list: "{{ mandatory_scripts }}"
        copy_scripts_path: "{{ remote_script_directory }}/"
        copy_scripts_group_name: devops
  tags: scripts

- name: Prepare BackUp Config
  hosts: synology_storage_nodes
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_list:
          - "{{ backup_script }}"
        copy_scripts_path: "{{ remote_script_directory }}/"
        copy_scripts_group_name: devops

    - role: offsite_backup
      become: true
  tags: backup
