- name: Bootstrap PiHole
  hosts: pihole_nodes
  become: true
  roles:
    - role: manage-keepalived
      vars:
        manage_keepalived_state: stopped
    - role: bootstrap-pi
    - role: apt-updates
    - role: manage-keepalived
      vars:
        manage_keepalived_state: started

- name: Copy Mandatory Scripts
  hosts: pihole_nodes
  roles:
    - role: copy-scripts
      vars:
        scripts:
          - '../launchpad-scripts/power/shutdown.sh'
          - '../launchpad-scripts/power/reboot.sh'
        remote_directory: '/home/serveradmin/scripts/'
  tags: scripts

- name: Setup docker
  hosts: pihole_nodes
  become: true
  roles:
    - role: manage-keepalived
      vars:
        manage_keepalived_state: stopped
    - role: setup-docker
    - role: manage-keepalived
      vars:
        manage_keepalived_state: started
  tags: docker

- name: Copy module folders
  hosts: pihole_nodes
  roles:
    - role: copy-module-folders
      vars:
        modules:
          pihole: '../launchpad-docker/pihole'
    - role: update-docker-compose-service
      vars:
        compose_path: '/home/{{ server_admin_user }}/pihole'
  tags: pihole

- name: Setup HA Master
  hosts: pihole_master
  roles:
    - role: keepalived
      vars:
        keepalived_: '/home/{{ server_admin_user }}/pihole'
  tags:
    - ha
    - master

- name: Setup HA Slaves
  hosts: pihole_slaves
  roles:
    - role: keepalived
      vars:
        keepalived_: '/home/{{ server_admin_user }}/pihole'
  tags:
    - ha
    - slaves
