- name: Set Detected System
  hosts: all
  roles:
    - role: set-detected-system
  tags:
    - superuser
    - mergekeys

- name: Create Server Admin User
  hosts: all
  roles:
    - role: add-sudo-user
      vars:
        username: "{{ server_admin_user_name }}"
        password: "{{ server_admin_user_password }}"
        admin_groups:
          - devops
  tags: superuser

- name: Merge public keys
  hosts: all
  roles:
    - role: update-authorized-key
      vars:
        username: "{{ server_admin_user_name }}"
        keys:
          - id_ed25519_homelab_asiri-devops
      become: true
  tags: mergekeys
