- name: Bootstrap
  hosts: capella-vm-101-semaphore
  become: true
  roles:
    - role: apt_updates
  tags: bootstrap

- name: Setup docker
  hosts: capella-vm-101-semaphore
  become: true
  roles:
    - role: setup_docker
  tags: bootstrap

- name: Copy module folders
  hosts: capella-vm-101-semaphore
  roles:
    - role: copy_scripts
  vars:
    copy_scripts_modules:
      - "../launchpad-docker/semaphore"
  tags: mods
