- name: Create Home Assistant Access User
  hosts: all
  gather_facts: false
  roles:
    - role: add-sudo-user
      become: true
      become_user: root
      vars:
        username: '{{ ha_access_user_name }}'
        user_shell: '/bin/bash'
        admin_groups:
          - devops
        permissions:
          become_user: "{{ server_admin_user_name }}"
          allowed_commands:
            - "/home/{{ server_admin_user_name }}/scripts/reboot.sh"
            - "/home/{{ server_admin_user_name }}/scripts/shutdown.sh"
    - role: update-authorized-key
      become: true
      vars:
        username: '{{ ha_access_user_name }}'
        keys:
          - id_ed25519_homelab_ha-access
  tags: haaccess

- name: Create DevOps User
  hosts: all
  gather_facts: false
  roles:
    - role: add-sudo-user
      become: true
      become_user: root
      vars:
        username: '{{ devops_access_user_name }}'
        user_shell: '/bin/bash'
        admin_groups:
          - devops
        permissions:
          become_user: "{{ server_admin_user_name }}"
          allowed_commands:
            - "/home/{{ server_admin_user_name }}/scripts/backup-pi.sh"
    - role: update-authorized-key
      become: true
      vars:
        username: '{{ devops_access_user_name }}'
        keys:
          - id_ed25519_homelab_devops-access
  tags: devopsaccess
