- name: Install Packages
  hosts: portainer_nodes
  roles:
    - role: apt_updates
      become: true
    - role: install_packages
      become: true
      vars:
        install_packages_custom_packages:
          - python3-requests
          - autofs
          - nano
  tags: bootstrap

- name: Setup docker
  hosts: portainer_nodes
  roles:
    - role: setup_docker
  tags: bootstrap

- name: Setup Primary Portainer Node
  hosts: iris
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_modules:
          - '../launchpad-docker/portainer'
    - role: docker_compose_service
      vars:
        docker_compose_service_path: '/home/{{ server_admin_user }}/portainer'
  tags: primary

- name: Copy Portainer Agents to Slaves
  hosts: portainer_slaves
  roles:
    - role: copy_scripts
      vars:
        copy_scripts_modules:
          - '../launchpad-docker/portainer-agent'
    - role: docker_compose_service
      vars:
        docker_compose_service_container_name: 'portainer-agent'
        docker_compose_service_path: '/home/{{ server_admin_user }}/portainer-agent'
  tags: slaves
