- name: Set Detected System
  hosts: all
  roles:
    - role: set-detected-system
  tags:
    - haaccess
    - devopsaccess

- name: sssss
  hosts: all
  tasks: 
    - name: one
      debug:
        var: ha_user_allowed_commands

    - name: one
      debug:
        var: devops_user_allowed_commands
  tags: print

- name: Setup Home Assistant Access User
  hosts: all
  gather_facts: false
  become: true
  roles:
    - role: add-sudo-user
      become_user: root
      vars:
        username: "{{ ha_access_user_name }}"
        admin_groups:
          - devops
        permissions:
          become_user: "{{ server_admin_user_name }}"
          allowed_commands: "{{ ha_user_allowed_commands }}"

    - role: update-authorized-key
      vars:
        username: "{{ ha_access_user_name }}"
        keys:
          - id_ed25519_homelab_ha-access
  tags: haaccess

- name: Setup DevOps User
  hosts: all
  gather_facts: false
  become: true
  roles:
    - role: add-sudo-user
      become_user: root
      vars:
        username: "{{ devops_access_user_name }}"
        admin_groups:
          - devops
        permissions:
          become_user: "{{ server_admin_user_name }}"
          allowed_commands: "{{ devops_user_allowed_commands }}"

    - role: update-authorized-key
      vars:
        username: "{{ devops_access_user_name }}"
        keys:
          - id_ed25519_homelab_devops-access
  tags: devopsaccess
