---
### --- node ip's ---
all:
  hosts:
    atlas:
      ansible_host: 172.16.20.2
    capella:
      ansible_host: 172.16.20.5
    iris:
      ansible_host: 172.16.20.8
    capella-vm-100:
      ansible_host: 172.16.20.40
    capella-vm-101:
      ansible_host: 172.16.20.41
    auriga-vm-102:
      ansible_host: 172.16.20.42
    auriga-vm-103:
      ansible_host: 172.16.20.43
    archivebox-ct:
      ansible_host: 172.16.20.45
    snipeit-ct:
      ansible_host: 172.16.20.48
    hoader-ct:
      ansible_host: 172.16.20.52

### ----------- storage nodes --------------
storage_nodes:
  hosts:
    nas-01-synology:
    rezerva:

### ----------- proxmox nodes -------------
proxmox_nodes:
  hosts:
    atlas:
    capella:

### ----------- proxmox vms ---------------
proxmox_vms:
  hosts:
    capella-vm-100:
    capella-vm-101:
    auriga-vm-102:
    auriga-vm-103:

### ----------- archivebox ----------------
archive_box:
  hosts:
    archivebox-ct:

### ----------- archivebox ----------------
snipeit_box:
  hosts:
    snipeit-ct:

### --------------- hoader ----------------
hoader_box:
  hosts:
    hoader-ct:
