portainer_nodes:
  hosts:
    iris:
    pavo-vm-100-media-server:
    pavo-vm-101-archiver:
    pavo-ct-102-finance:

portainer_master:
  hosts:
    iris:

portainer_slaves:
  hosts:
    pavo-vm-100-media-server:
    pavo-vm-101-archiver:
    pavo-ct-102-finance:
