---
all:
  hosts:
    nas-01-synology:
      ansible_host: 172.16.20.3
    rezerva:
      ansible_host: 172.16.20.7

storage_nodes:
  hosts:
    nas-01-synology:
    rezerva:

general_storage_nodes:
  hosts:
    rezerva:

synology_storage_nodes:
  hosts:
    nas-01-synology:
