- name: Setup Synology sudo User
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/syno/sbin:/var/services/homes/{{ ansible_user }}/scripts"
  become: true
  block:
    - name: Add User
      ansible.builtin.command: synology-manage-user.sh "{{ sudo_user_username }}" "{{ sudo_user_password | default('') }}"
      register: result
      changed_when: '"user already exists" not in result.stdout'

- name: Setup Groups for Synology sudo User
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/syno/sbin:/var/services/homes/{{ ansible_user }}/scripts"
  become: true
  block:
    - name: Append Administrator Group
      ansible.builtin.set_fact:
        internal_admin_groups: "{{ (sudo_user_admin_groups | default([])) + ['administrators'] }}"

    - name: Add to Groups
      ansible.builtin.command: synology-manage-group.sh "{{ sudo_user_username }}" "{{ item }}"
      register: result
      loop: "{{ internal_admin_groups }}"
      changed_when: '"user is already a member of group" not in result.stdout'

- name: Enable sudo Accesss
  become: true
  ansible.builtin.template:
    src: ./templates/sudoers.j2
    dest: "/etc/sudoers.d/{{ sudo_user_username }}"
    owner: root
    group: root
    mode: "0600"
  vars:
    user_permissions: "{{ psudo_user_permissions | default({'allowed_commands': []}) }}"

- name: Update Permissions to Allow Passworld-less Access
  become: true
  block:
    - name: Change Home Directory Permissions
      ansible.builtin.file:
        path: "/var/services/homes/{{ sudo_user_username }}"
        state: directory
        mode: "0711"

    - name: Change ssh Directory Permissions
      ansible.builtin.file:
        path: "/var/services/homes/{{ sudo_user_username }}/.ssh"
        state: directory
        mode: "0711"
