# - name: Ensure Backup Script Exist
#   ansible.builtin.file:
#     path: "{{  }}"
#     state: file
#     owner: "{{ server_admin_user }}"
#     group: "{{ server_admin_user }}"
#     mode: '0775'

# - name: Ensure Backup Folder Exists
#   ansible.builtin.file:
#     path: "{{  }}"
#     state: directory
#     owner: "{{ server_admin_user }}"
#     group: "{{ server_admin_user }}"
#     mode: 0775

- name: Start Backup
  ansible.builtin.command: "bash -s < /home/serveradmin/scripts/backup-pi.sh"
