- name: Start Backup
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/syno/sbin:/var/services/homes/serveradmin/scripts"
  ansible.builtin.command: "sudo {{ remote_script_directory }}/backup.sh"
