# - name: Ensure Backup Script Exist
#   ansible.builtin.file:
#     path: "{{  }}"
#     state: file
#     owner: "{{ server_admin_user_name }}"
#     group: "{{ server_admin_user_name }}"
#     mode: '0775'

# - name: Ensure Backup Folder Exists
#   ansible.builtin.file:
#     path: "{{  }}"
#     state: directory
#     owner: "{{ server_admin_user_name }}"
#     group: "{{ server_admin_user_name }}"
#     mode: 0775

- name: Backup Device
  ansible.builtin.include_tasks: "backup_{{ detected_system }}.yaml"
# - name: Start Backup
#   ansible.builtin.command: sudo /home/serveradmin/scripts/backup-pi.sh
