- name: Set Detected System to Unknown
  ansible.builtin.set_fact:
    detected_system: "unknown"

- name: Check if Synology
  when: detected_system == 'unknown'
  block:
    - name: Check if detected_system can be Synology
      ansible.builtin.set_fact:
        detected_system: "synology"
      when: ansible_system_vendor == 'Synology Inc.'

- name: Check if Raspbian
  when: detected_system == 'unknown'
  block:
    - name: Check Kernel Symbols
      ansible.builtin.command: grep -q raspberrypi /proc/kallsyms
      register: picheck
      failed_when: false
      changed_when: false

    - name: Check if detected_system can be Raspibian
      ansible.builtin.set_fact:
        detected_system: "raspbian"
      when: picheck.rc == 0
