- name: Download and Unzip Pi Image Tools
  ansible.builtin.unarchive:
    src: https://files.networkprofile.org/s/ZebFWQKqra7LgJr/download/image-files.zip
    dest: /usr/local/bin
    group: "{{ server_admin_user }}"
    owner: "{{ server_admin_user }}"
    mode: "700"
    remote_src: true

- name: Install Required Packages
  ansible.builtin.package:
    name:
      - rsync
      - expect
    state: present

- name: Setup Image Backup
  ansible.builtin.shell: |
    image-backup

    expect "OK to install gdisk (y/n)?"
    send y

    expect "Image file to create?"
    send \x03

    exit 0
  args:
    executable: /usr/bin/expect
