- name: Download and Unzip Pi Image Tools
  ansible.builtin.unarchive:
    src: https://files.networkprofile.org/s/ZebFWQKqra7LgJr/download/image-files.zip
    dest: /usr/local/bin
    group: "{{ server_admin_user_name }}"
    owner: "{{ server_admin_user_name }}"
    mode: "700"
    remote_src: true

- name: Install Required Packages
  ansible.builtin.package:
    name:
      - rsync
      - python3-pexpect
    state: present

- name: Setup Image Backup
  ansible.builtin.expect:
    command: image-backup
    responses:
      "Ok to install gdisk (y/n)?": "y"
      "Image file to create?": "\x03"
    timeout: 120
  ignore_errors: True
