---
- name: Create sudo user
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password }}"
    shell: "{{ user_shell }}"
  when: password is defined
  become: true

- name: Create sudo user
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ user_shell }}"
  when: password is undefined
  become: true
