- name: Create Group
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ admin_groups }}"
  when: admin_groups is defined

- name: Add to Group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: "{{ admin_groups }}"
    append: true
  when: admin_groups is defined
