- name: Print all available facts
  ansible.builtin.debug:
    msg: "{{ lookup('template', 'keepalived.conf.j2') }}"

- name: Enable nonlocal IP binding
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.ip_nonlocal_bind = 1
      net.ipv6.ip_nonlocal_bind = 1
  notify: Reload sysctl config

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install keepalived
  ansible.builtin.apt:
    force_apt_get: true
    name: keepalived

- name: Copy check_pihole.sh
  ansible.builtin.copy:
    dest: /etc/keepalived/check_pihole.sh
    src: check_pihole.sh
    mode: "0755"

- name: Configure keepalived
  ansible.builtin.template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.conf.j2
    mode: "0644"
  notify: Restart keepalived service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
